# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Titulo', models.CharField(max_length=100)),
                ('Foto', models.CharField(max_length=100)),
                ('DescripcionFoto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Directiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaDeInicio', models.DateField()),
                ('FechaDeFinalización', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('FechaDeInicioEstimada', models.DateField()),
                ('HoraDeInicioEstimada', models.TimeField()),
                ('FechaDeFinalizaciónEstimada', models.DateField()),
                ('HoraDeFinalizaciónEstimada', models.TimeField()),
                ('Estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('FechaDeInicioEstimada', models.DateField()),
                ('FechaDeFinalizaciónEstimada', models.DateField()),
                ('Estado', models.CharField(max_length=20)),
                ('Manzana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Manzana')),
                ('Responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Habitante')),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Evidencia', models.CharField(max_length=100)),
                ('Persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Habitante')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIngresoEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Evidencia', models.CharField(max_length=100)),
                ('Manzana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Manzana')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRegistroDeDinero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='registroingresoegreso',
            name='Tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TipoRegistroDeDinero'),
        ),
        migrations.AddField(
            model_name='registroingresoegreso',
            name='Villa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Villa'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='Manzana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Manzana'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='Villa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Villa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='Manzana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Manzana'),
        ),
        migrations.AddField(
            model_name='evento',
            name='Responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='CuartoVocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_CuartoVocal', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='Presidente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_Presidente', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='PrimerVocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_PrimerVocal', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='Secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_Secretaria', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='SegundoVocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_SegundoVocal', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='Sindico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_Sindico', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='TercerVocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_TercerVocal', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='Tesorero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_Tesorero', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='VicePresidente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Directiva_VicePresidente', to='app.Habitante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Evento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Habitante'),
        ),
    ]
