# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_proyecto_manzana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='FechaDeFinalizaciónEstimada',
            new_name='FechaDeFinalizacionEstimada',
        ),
    ]
