# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_evento_manzana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='FechaDeFinalizaciónEstimada',
            new_name='FechaDeFinalizacionEstimada',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='HoraDeFinalizaciónEstimada',
            new_name='HoraDeFinalizacionEstimada',
        ),
    ]
