# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181017_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendicionDeCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.PositiveSmallIntegerField(null=True)),
                ('MesNumero', models.PositiveSmallIntegerField(null=True)),
                ('MesNombre', models.CharField(max_length=20)),
                ('Tipo', models.CharField(max_length=100)),
                ('Titulo', models.CharField(max_length=100)),
                ('Valor', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tiporegistrodedinero',
            old_name='Tipo',
            new_name='Categoria',
        ),
    ]
