# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181017_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RendicionDeCuentas',
            new_name='rptRendicionDeCuentas',
        ),
    ]
