# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181017_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rptrendiciondecuentas',
            old_name='MesNumero',
            new_name='Orden',
        ),
    ]
